name: QTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.12.8'
        host: 'linux'
        target: 'desktop'
#        modules: 'qtcharts'
#        tools: 'tools_qtcreator,qt.tools.qtcreator'

#        cd tests && qmake test-convertisseur.pro && make && ./test-convertisseur.out -platform minimal    
    - name: Run qmake/qtest
      id: qtest
      continue-on-error: true
      shell: bash
      run: |      
        label="qtest"
        echo "##[set-output name=label;]${label}"
        cd tests && qmake test-convertisseur.pro && make && ./test-convertisseur.out -platform offscreen
        res=$?
        if [ $res -eq 0 ]
        then
          retour="passing"
          color="green"
        else
          retour="failing"
          color="red"
        fi
        echo "##[set-output name=status;]${retour}"
        echo "##[set-output name=color;]${color}"

    # switch to badges branch
    - run: |
        git checkout badge_qtest || git checkout -b badge_qtest
        test -d .github/badges || mkdir -p .github/badges

    # create badge
    - name: badge
      uses: emibcn/badge-action@v1.2.1
      with:
        label: ${{ steps.qtest.outputs.label }}
        status: ${{ steps.qtest.outputs.status || 'failing' }}
        color: ${{ steps.qtest.outputs.color || 'red' }}
        path: '.github/badges/badge_qtest.svg'

    # commit and push badges if badges have changed
    - name: Commit changes to badge
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add '.github/badges/badge_qtest.svg'
        git commit -m "Add/Update badge_qtest" || exit 0
        git push -f origin badge_qtest
